"""Add image field to cactus model.

Revision ID: ac74bb929a1d
Revises: 565d16afd741
Create Date: 2022-06-05 14:12:25.620212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac74bb929a1d'
down_revision = '565d16afd741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cactus', sa.Column('image', sa.Unicode(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cactus', 'image')
    # ### end Alembic commands ###
