"""Add product model.

Revision ID: c64eaeac6b5a
Revises: ac74bb929a1d
Create Date: 2022-06-18 11:15:24.763487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c64eaeac6b5a'
down_revision = 'ac74bb929a1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('related_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.Unicode(length=128), nullable=False),
    sa.Column('cactus_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cactus_id'], ['cactus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related_product')
    # ### end Alembic commands ###
